import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import { useUserStore } from "../store/user";

const Home: NextPage = () => {
  const login = useUserStore((state) => state.login);
  const user = useUserStore((state) => state.user);
  return (
    <div>
      <Head>
        <title>Onboarding - LBL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {user.loggedIn ? (
          <h2>Welcome</h2>
        ) : (
          <Button colorScheme="blue" onClick={login}>
            Login
          </Button>
        )}
      </main>
    </div>
  );
};

export default Home;
